# Generated by Django 5.1 on 2024-08-09 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xodimlar_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='davomat',
            name='jamoa',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='jamoa',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('isinstance', models.BooleanField(default=False)),
                ('xodimlar_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='main.xodimlar_name')),
            ],
        ),
        migrations.DeleteModel(
            name='Damovat_olish',
        ),
        migrations.DeleteModel(
            name='Davomat',
        ),
        migrations.DeleteModel(
            name='Jamoa',
        ),
        migrations.DeleteModel(
            name='Xodimlar',
        ),
    ]
